/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_serial_number_string           20
#define gattdb_hardware_revision_string       22
#define gattdb_firmware_revision_string       24
#define gattdb_software_revision_string       26
#define gattdb_system_id                      28
#define gattdb_ieee_11073_20601_regulatory_certification_data_list 30
#define gattdb_pnp_id                         32
#define gattdb_rgb_state                      35
#define gattdb_gesture_state                  39
#define gattdb_ota_control                    43


#endif // __GATT_DB_H
